security:
    enable_authenticator_manager: true

    hide_user_not_found: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\UserNd
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
#            entry_point: App\Security\LoginFormAuthenticator
            entry_point: form_login
            custom_authenticator:
#                - App\Security\AndesFormAuthenticator
#                - App\Security\LoginFormAuthenticator
                - App\Security\DummyAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true

            logout: true


            remember_me:
                secret: '%kernel.secret%'
#                always_remember_me: true
                signature_properties: [password]


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    role_hierarchy:
        ROLE_ADMIN_SITE: ['ROLE_ALLOWED_TO_SWITCH']
        ROLE_ADMIN: [ 'ROLE_COMMENT_ADMIN', 'ROLE_USER_ADMIN' ]
        ROLE_HUMAN_RESOURCES: [ 'ROLE_USER_ADMIN' ]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin/login, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
